from django.urls import path
from .views import (
    Classrooms, ClassroomDetail,
    Deliveries, DeliveryDetail, 
    Students, StudentDetail,
    UtilDeliveries, UtilDeliveryDetail, MoneyDeliveries, MoneyDeliveryDetail,
    Lists, ListDet, ListDetails, ListDetailDetail,
    Notifications, NotificationDetail, Adressees, AdresseeDetail,
    Purchases, PurchaseDet, PurchaseDetails, PurchaseDetailDetail,
    Requests, RequestDet, RequestDetails, RequestDetailDetail,
    Users, UserDetail, Groups, GroupDetail, Profiles, ProfileDetail,
    Utils, UtilDetail
)

urlpatterns = [
    path('classrooms/', Classrooms.as_view()),
    path('classrooms/<uuid:pk>/', ClassroomDetail.as_view()), 
    path('deliveries/', Deliveries.as_view()),
    path('deliveries/<uuid:pk>/', DeliveryDetail.as_view()),
    path('students/', Students.as_view()),
    path('students/<uuid:pk>/', StudentDetail.as_view()),
    path('util-deliveries/', UtilDeliveries.as_view()),
    path('util-deliveries/<uuid:pk>/', UtilDeliveryDetail.as_view()),
    path('money-deliveries/', MoneyDeliveries.as_view()),
    path('money-deliveries/<uuid:pk>/', MoneyDeliveryDetail.as_view()),
    path('lists/', Lists.as_view()),
    path('lists/<uuid:pk>/', ListDet.as_view()),
    path('list-details/', ListDetails.as_view()),
    path('list-details/<uuid:pk>/', ListDetailDetail.as_view()),
    path('notifications/', Notifications.as_view()),
    path('notifications/<uuid:pk>/', NotificationDetail.as_view()),
    path('adressees/', Adressees.as_view()),
    path('adressees/<uuid:pk>/', AdresseeDetail.as_view()),
    path('purchases/', Purchases.as_view()),
    path('purchases/<uuid:pk>/', PurchaseDet.as_view()),
    path('purchase-details/', PurchaseDetails.as_view()),
    path('purchase-details/<uuid:pk>/', PurchaseDetailDetail.as_view()),
    path('requests/', Requests.as_view()),
    path('requests/<uuid:pk>/', RequestDet.as_view()),
    path('request-details/', RequestDetails.as_view()),
    path('request-details/<uuid:pk>/', RequestDetailDetail.as_view()),
    path('users/', Users.as_view()),
    path('users/<uuid:pk>/', UserDetail.as_view()),
    path('groups/', Groups.as_view()),
    path('groups/<uuid:pk>/', GroupDetail.as_view()),
    path('profiles/', Profiles.as_view()),
    path('profiles/<uuid:pk>/', ProfileDetail.as_view()),
    path('utils/', Utils.as_view()),
    path('utils/<uuid:pk>/', UtilDetail.as_view()),
]